version: '3.7'
services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:7.0.0-alpine
    command: redis-server
    volumes:
      - /var/lib/redis/data
    ports:
      - "6379:6379"
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py autoreload -- celery -A pycharm_bug worker -l info
    volumes:
      - ..:/app
    env_file: .env
    depends_on:
      - django
      - redis